#!/usr/bin/env bash
#++ install Haproxy load balancer

# colors
blue='\e[1;34m'
brown='\e[0;33m'
reset='\033[0m'

echo -e "${brown}Installing and configuring HAproxy...${reset}\n\n"

sudo apt-get update

sudo apt-get install -y haproxy

# enable haproxy to start on boot
sudo systemctl enable haproxy

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default_conf.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend jralx-tech-frontend
    bind *:80
    stats uri /haproxy?stats
    default_backend jralx-tech-backend

backend jralx-tech-backend
    balance roundrobin
    server 308890-web-01 54.88.9.85:80 check
    server 308890-web-02 54.162.43.160:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "${blue}HAproxy configuration complete...${reset}\n\n"
