#!/usr/bin/env bash
#++This script configures Nginx to listen on port 80 of all the server’s active IPv4 IPs but status if nginx"not running"
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
