#!/usr/bin/env bash
# Function to clean up and exit

cleanup_exit()
{
	echo "Cleaning up and exiting..."
	rm -f /var/run/myscript.pid
	exit
}

# Trap SIGTERM and SIGQUIT signals to cleanup and exit

trap 'cleanup_exit' SIGTERM SIGQUIT

# Trap SIGINT signal to display a message

trap 'echo "Y U no love me?!"' SIGINT

# Trap SIGTERM signal to display a message

trap 'echo "I hate the kill command"' SIGTERM

# Get process ID and save to file

echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely

echo "To infinity and beyond"

while true
do
	sleep 1
done
