#!/usr/bin/env bash
# Function to clean up and exit

cleanup_exit()
{
	echo "Cleaning up and exiting..."
	rm -f /var/run/myscript.pid
	exit
}

# Get pid of and save on file
echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	
	sleep 2
	
	trap 'echo "Y U no love me?!"' SIGINT
	
	trap 'echo "I hate the kill command"' SIGTERM
	
	trap 'cleanup_exit' SIGTERM SIGQUIT
done
