#!/usr/bin/env bash
# Displays numbers from 1 to 100
#+	display:
#+		FizzBuzz when number is multiple of 3 and 5
#+		Fizz when number is multiple of 3
#+		Buzz when number is multiple of 5 otherwise number

number=1
LIMIT=100

while (( number <= LIMIT)); do

	if ! ((number % 3)) && ! ((number % 5)); then
		echo "FizzBuzz"
	elif ! ((number % 3)); then
		echo "Fizz"
	elif ! ((number % 5)); then
		echo "Buzz"
	else
		echo "$number"
	fi

	((number++))
done
