#!/usr/bin/env bash
# A script to display Best School 10 times using while loop if 9 say Hi

text="Best School"
LIMIT=10
i=1

while (( i <= LIMIT)); do
	echo "$text"

	# display hi if in 9th iteration
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi

	((i++))
done

exit 0
