#!/usr/bin/env bash
# Script to display numbers from 1 to 2 and after 4th, 9th and 17th iter
# display bad luck from china, japan and italy respectively

LIMIT=20
i=1

while (( i <= LIMIT)); do

	echo "$i"

	case "$i" in
		4 )
			echo "bad luck from China";;
		9 )
			echo "bad luck from Japan";;
		17 )
			echo "bad luck from Italy";;
	esac

	((i++))

done
