#!/usr/bin/env bash
# A script that gives you information about the school file

file="school"

# check if file exist
if [ -e "$file" ]; then

	echo "school file exists"

	# if file is empty
	if [ ! -s "$file" ]; then
		
		echo "school file is empty"
		
		# is file a regular file
		if [ -f "$file" ]; then
			echo "school is a regular file"
		fi

	else
		
		echo "school file is not empty"
		
		# is file a regular file
		if [ -f "$file" ]; then
			echo "school is a regular file"
		fi
	fi

else
	echo "school file does not exist"
fi
